### ISSUE TITLE
distance and time conversion

### ISSUE THREAD

**Issue by MichaelGluszek** [trilogy-quadrant/Project1#31]
meters to miles, minutes to hours and minutes

**Comment by DanielSochor** [comment]
Thought you were locating the distance in jfiddle link I sent

**Comment by MichaelGluszek** [comment]
i want to take a shot at it before you get back from work. i could use the
javascript contributions if i manage to figure it out.

**Comment by DanielSochor** [comment]
Cool, this link will be easier than doing it in the actual file:

http://jsfiddle.net/gh/get/jquery/2.1.0/heremaps/jsfiddle-github/tree/master/map-with-route-from-a-to-b

**Comment by DanielSochor** [comment]
Fixed both these issues
